name: Update Quotes

on:
  schedule:
    - cron: '30 3 * * *'  # 9:00 AM IST daily
  workflow_dispatch:

jobs:
  update-quotes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.5'

    - name: Install requests module
      run: pip install requests

    - name: Run update_quotes.py
      run: python networking/update_quotes.py

    - name: Commit and push changes
      run: |
        git config --local user.name "particle-box"
        git add networking/quotes.json
        git commit -m "bot(scripts): Daily Quotes Update"
        git push
